### ISSUE TITLE
RPM Fails to install on Centos 7.2

### ISSUE THREAD

**Issue by ViViDboarder** [StratoSource/StratoSource#43]
Running `dnf install stratosource.rpm` yeilds the following error:

```
==> default: Failed to open: /var/cache/dnf/x86_64/7/x86_64/7/epel/repodata/7606091f906d2ce00f0964599ef82d349a9231362d4ec3068c7f8f3d1f237b13-updateinfo.xml.bz2.
```

This is repeatable with my Vagrant box using base image "bento/centos-7.2" and a very simple bootstrap.sh script:

```
# Install prereqs
yum -y install epel-release
yum -y install dnf

# StratoSource
rpm_name=stratosource-2.0.1-0.noarch.rpm
wget https://github.com/StratoSource/StratoSource/raw/master/latest/$rpm_name
dnf install -y $rpm_name
```

**Comment by mlsmithjr** [comment]
You can substitute yum for dnf on RHEL and CentOs.  The dnf tool is
applicable only for Fedora.  I'll check the docs and correct.

**Comment by ViViDboarder** [comment]
I ended up doing that. Thanks!
